application: aeon-xando
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: django_rocket.wsgi

libraries:
- name: django
  version: 1.3

skip_files:
- ^.google_appengine/*.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$